server:
  port: 10006
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
  servlet:
    context-path: /v1/api/

swagger:
  enable: true

spring:
  application:
    name: consumer2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://rm-bp1oydriw2vi7fc68qo.mysql.rds.aliyuncs.com:3306/saas_prelending?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=Asia/Shanghai
      username: user_saas
      password: Lunz2017
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.6.63:9092
          zk-nodes: 127.0.0.1:2181
          minPartitionCount: 1
          autoCreateTopics: true
          autoAddPartitions: true
          required-acks: 1
          health-timeout: 120
      bindings:
        common_input:
          destination: stream-demo
          content-type: text/plain
        group_input:
          destination: stream-group-demo
          content-type: text/plain
          group: demo-group
        trans_input:
          destination: stream-trans-demo-1
          content-type: text/plain
        partition_input:
          destination: stream-partition-demo
          content-type: text/plain
          group: partition-group
        header_input:
          destination: stream-header-demo
          content-type: text/plain

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/**Mapper.xml
  type-aliases-package: "com.rgs.template.entity"
