server:
  port: 10004
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
  servlet:
    context-path: /v1/api/

swagger:
  enable: true

spring:
  application:
    name: Producer

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://rm-bp1oydriw2vi7fc68qo.mysql.rds.aliyuncs.com:3306/saas_prelending?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=Asia/Shanghai
      username: user_saas
      password: Lunz2017
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.6.63:9092 #Kafka的消息中间件服务器
          zk-nodes: 127.0.0.1:2181 #Zookeeper的节点，如果集群，后面加,号分隔
          minPartitionCount: 1 #标识最小分区数量
          autoCreateTopics: true #如果设置为false,就不会自动创建Topic 有可能你Topic还没创建就直接调用了。
          autoAddPartitions: true #自动创建partition
          required-acks: 1 #标识是否需要ack
          health-timeout: 120
      bindings:
        common_output: #与对应Source接口中Output注解的value一致
          destination: stream-demo #Kafka中topic的名字
          content-type: text/plain
        group_output:
          destination: stream-group-demo
          content-type: text/plain
        trans_output:
          destination: stream-trans-demo
          content-type: text/plain
        partition_output:
          destination: stream-partition-demo
          content-type: text/plain
          producer:
            partitionKeyExpression: payload #取模表达式，系统会根据payload%partition count来向某一个partition放数据
            partitionCount: 2 #指定该topic需要建立多少个partition，必须配合autoAddPartitions: true使用
        header_output:
          destination: stream-header-demo
          content-type: text/plain

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/**Mapper.xml
  type-aliases-package: "com.rgs.template.entity"
